### ISSUE TITLE
DCGM exporter is not working on AWS A10 instances (G5.2xlarge, G5.12xlarge)

### ISSUE THREAD

**Issue by vickeyrihal1** [NVIDIA/go-dcgm#15]
We recently added AWS G5(A10) tier to our Kubernetes clusters. The applications are running alright on the new tier. However the DCGM exporter pods are have a tough time with scheduling and going into CRASHLOOPBACKOFF.

**DCGM Version:** 2.3.2-2.6.3-ubuntu20.04
**NVIDIA driver version:** 460.106.00
**OS/Flatcar version:** 3139.2.0
**Kernel:** 5.15.32-flatcar

**Logs:**
`root@bb23c6bb6001:/infrastructure# k logs dcgm-exporter-w9fhs -n monitoring  dcgm-exporter
time="2022-05-27T08:53:58Z" level=info msg="Starting dcgm-exporter"
time="2022-05-27T08:53:58Z" level=info msg="DCGM successfully initialized!"
time="2022-05-27T08:53:59Z" level=info msg="Collecting DCP Metrics"
time="2022-05-27T08:53:59Z" level=fatal msg="Error watching fields: Feature not supported"
root@bb23c6bb6001:/infrastructure#`

**Comment by glowkey** [comment]
We need more information to determine the cause of this failure, specifically the log file from the container in /var/log/nv-hostengine.log. You could change entry point of the dcgm-exporter container to a long sleep then log into the container, execute /usr/local/dcgm/dcgm-exporter-entrypoint.sh then export the log in /var/log/nv-hostengine.log.

**Comment by nikkon-dev** [comment]
@vickeyrihal1, 

A10 does not support the 1006 metric (DCGM_FI_PROF_PIPE_FP64_ACTIVE). Please, check if you have it in your dcgm-exporter config.

**Comment by vickeyrihal1** [comment]
Cool! the pods became stable after removing DCGM_FI_PROF_PIPE_FP64_ACTIVE from config map. Thanks.
