### ISSUE TITLE
Segfault using result of FieldValue_v1.String()

### ISSUE THREAD

**Issue by bmerry** [NVIDIA/go-dcgm#18]
While trying to implement https://github.com/NVIDIA/dcgm-exporter/issues/72 I've encountered a segfault when trying to use DCGM_FI_DRIVER_VERSION; specifically if I try to format the result of `FieldValue_v1.String()`.

I've only written a few hundred lines of Go in my life, but [this](https://github.com/NVIDIA/go-dcgm/blob/ede63d11c9e7d11f17f217648a1adfc824db37df/pkg/dcgm/fields.go#L169) looks suspicious: it's directly casting a C NUL-terminated string to a Go `string`, rather than using [C.GoString](https://github.com/golang/go/wiki/cgo#go-strings-and-c-strings).

**Comment by nikkon-dev** [comment]
Hi @bmerry,

Thank you for the report!

Yes, you are right, that's a bug. As you could see from several lines [below](https://github.com/NVIDIA/go-dcgm/blob/ede63d11c9e7d11f17f217648a1adfc824db37df/pkg/dcgm/fields.go#L189), the strings are should be handled differently.

**Comment by glowkey** [comment]
Fixed with MR#19
