### ISSUE TITLE
monitor job statistic

### ISSUE THREAD

**Issue by laolaoMonkey** [NVIDIA/go-dcgm#20]
Hello, i want to use go-dcgm to monitor job statistic which may use API "dcgmJobStartStats" and "dcgmJobStopStats". Do you have a plan to implements it? Hope your reply.

**Comment by glowkey** [comment]
We do have intentions for the full DCGM API in the go-dcgm bindings but we do not have a timeframe.

**Comment by laolaoMonkey** [comment]
Okay, thank you.
