### ISSUE TITLE
 concurrent calls to the dcgm.GetProcessInfo() fucntion sometimes block

### ISSUE THREAD

**Issue by xigang** [NVIDIA/go-dcgm#24]
On T4 GPU machine, concurrent calls to the [dcgm.GetProcessInfo()](https://github.com/NVIDIA/go-dcgm/blob/main/pkg/dcgm/api.go#L86) function sometimes block. The  [dcgm.GetProcessInfo()](https://github.com/NVIDIA/go-dcgm/blob/main/pkg/dcgm/api.go#L86) function allow concurrent reqeust to the DCGM module?

this is my code:
```
func (nm *nvidiaManager) doWork(numDevices int) {
	ticker := time.NewTicker(nm.processMetricsInterval)
	for {
		select {
		case <-nm.dcgmDone:
			klog.Warningf("update nvidia device process info task exit.")
			return
		case <-ticker.C:
		}

		pidCh := make(chan devicePidItem, numDevices*2)
		wg := sync.WaitGroup{}
		for _, item := range devicePids {
			pidCh <- devicePidItem{minor: item.minor, pid: item.pid}
			wg.Add(1)
			go nm.handleDevicePid(pidCh, wg.Done)
		}
		wg.Wait()
	}
}

func (nm *nvidiaManager) handleDevicePid(pidCh chan devicePidItem, done func()) {
	defer done()
	for {
		select {
		case item := <-pidCh:
			start := time.Now()
			groupId, err := dcgm.WatchPidFields()
			if err != nil {
				_ = dcgm.DestroyGroup(groupId)
				return
			}

			// wait for watches to be enabled
			time.Sleep(3000 * time.Millisecond)

			klog.V(4).Infof("Enabling DCGM watches to start collecting process %v stats. cost time: %v", item.pid, time.Since(start))

			start = time.Now()
			processInfo, err := dcgm.GetProcessInfo(groupId, uint(item.pid))
			if err != nil {
				_ = dcgm.DestroyGroup(groupId)
				return
			}
			....
		default:
			return
		}
	}
}
```

[C.dcgmGetPidInfo](https://github.com/NVIDIA/go-dcgm/blob/32999852818dd53f97d0008414bb4dd3aff99f5b/pkg/dcgm/process_info.go#L107) method block.
![image](https://user-images.githubusercontent.com/3377677/192144822-0b456f43-f359-490f-b2b4-3193376c13ef.png)

C.dcgmGetPidInfo() block debug log.
![image](https://user-images.githubusercontent.com/3377677/192144861-52970e2e-4c11-4b3e-8d1e-1ce42e4ba2b5.png)

**Comment by glowkey** [comment]
This call is handled in the DCGM library (either embedded or running in the nv-hostengine). Could you provide DCGM version information and debug logs?

**Comment by xigang** [comment]
> ###

a

**Comment by xigang** [comment]
@glowkey  The implementation of the [dcgm.watchPidFields()](https://github.com/NVIDIA/go-dcgm/blob/main/pkg/dcgm/process_info.go#L70) creates a group and calls c.dgmwatchpidfields() function to request DCGM module for pid field data. 

Read [ DCGM Groups](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#groups) documentation and found that it is recommended not to create groups frequently and the maximum upper limit of the group is 64 (I speculate that it should be the limit of the GPU driver and device). Because I need to get GPU process metrics data frequently. So I cache the pid's dcgm.group through a `var groups = make(map[pid]dcgm.GroupHandle, 64)`. To reduce the performance overhead caused by high-frequency create and destory of dcgm.group.

Because the internal implementation of the dcgm.GetProcessInfo() function will call the C.dcgmGetPidInfo() function to get the pid process information, and finally call the C.dcgmGroupDestroy() function to destroy the dcgm.group. Frequent calls to the dcgm.GetProcessInfo() function will increase Overhead of the DCGM module. So we removed the dcgm.GetProcessInfo() inside the dcgm.GetProcessInfo() function. Control the destruction of the dcgm.group in our own code logic.

Hope it helps others.
