### ISSUE TITLE
dcgm.GetProcessInfo() function returns "No data is available"

### ISSUE THREAD

**Issue by SQUIDwarrior** [NVIDIA/go-dcgm#3]
I am trying to build a GPU stats collector into some of our tooling, and I am using the "dcgm.GetProcessInfo()" function to get data about various processes. I am trying to use DCGM in embedded mode so I do not have to install the full DCGM package into every host running in our system. However I am having trouble getting it to work reliably as I keep getting "No data is available" errors, similar to https://github.com/NVIDIA/gpu-monitoring-tools/issues/32. I modeled my implementation off the RestAPI example, specifically this: https://github.com/NVIDIA/go-dcgm/blob/main/samples/restApi/handlers/dcgm.go#L114

I am testing by doing the following:
1. Run `nbody` as myself in benchmark mode.
2. Run my stats collector code as root, passing in the PID of `nbody`

In the stats collector, this function is called in a loop, with a sleep of 1-10s between each call:
```golang
func (g *gpuStatManagerImpl) GetProcessInfo(pid uint) ([]stats.GPUStat, error) {
	if g.dcgmWatchGroup == nil {
		if err := g.watchPidFields(); err != nil {
			return nil, err
		}
		// If this is the first time this function as been called, sleep for 1s to allow stats collection to init
		time.Sleep(1 * time.Second)
	}

	pInfo, err := dcgm.GetProcessInfo(*g.dcgmWatchGroup, pid)
	if err != nil {
		return nil, err
	}
	gpuStats := make([]stats.GPUStat, len(pInfo))
	for i, p := range pInfo {
		gpuStats[i] = stats.GPUStat{
			DeviceID:          p.GPU,
			SMUtilization:     p.ProcessUtilization.SmUtil,
			MemoryUtilization: p.ProcessUtilization.MemUtil,
			PowerUsageJoules:  p.ProcessUtilization.EnergyConsumed,
		}
	}

	if err := g.watchPidFields(); err != nil {
		return gpuStats, err
	}

	return gpuStats, nil
}

func (g *gpuStatManagerImpl) watchPidFields() error {
	group, err := dcgm.WatchPidFields()
	if err != nil {
		return err
	}
	g.dcgmWatchGroup = &group
	return nil
}
```

I have tried using the go-dcgm RestAPI example, and the `processInfo` example, and both get the same "No data is available" error. Here is the nvidia-smi output of the GPU. As you can see, the `nbody` process is running:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   72C    P0    69W /  70W |   1484MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14335      C   ./nbody                          1481MiB |
+-----------------------------------------------------------------------------+
```

**Comment by SQUIDwarrior** [comment]
I should point out that sometimes this works, but most of the time it doesn't. It seems to be random.

**Comment by nikkon-dev** [comment]
Hello,

The `WatchPidFields` API will affect only processes that were started after this API is called. 
Try to first run the monitoring and then start the nbody process.

WBR,
Nik

**Comment by SQUIDwarrior** [comment]
Interesting. So the restAPI and the processInfo examples are just wrong? Because both of them take in a PID as an argument, which assumes the process to be monitored is started first, and then the monitoring after.

**Comment by nikkon-dev** [comment]
Unfortunately, yes. WatchPidFields effectively enables the accounting mode in the driver: [Link](https://docs.nvidia.com/deploy/nvml-api/group__nvmlAccountingStats.html). The processes that started before this mode was enabled are not augmented by the driver, and we cannot get stats for them.

**Comment by SQUIDwarrior** [comment]
Alright, I will try this with my code. The examples should probably be updated as this has caused me a lot of confusion and frustration as it seemed like my results were unpredictable. But thank you for the response! Will let you know how it goes.

**Comment by SQUIDwarrior** [comment]
@nikkon-dev This seems to work, so I think we can close this issue. However I would like to request the examples be better documented with the limitations and how to make the work as expected.
