### ISSUE TITLE
Question regarding MIG UUID

### ISSUE THREAD

**Issue by starry91** [NVIDIA/go-dcgm#30]
Is there a way to programmatically get the MIG GPU instance(GI) UUID from GPU ID and GI instance ID? [MigEntityInfo](https://github.com/NVIDIA/go-dcgm/blob/main/pkg/dcgm/mig.go#L50) contains only the parent device UUID.
nvidia-smi gives the UUID (`MIG-a65afc88-50b5-5ccf-b0a8-f93b3247ae9e`):
```
$ nvidia-smi -L
GPU 0: NVIDIA A100 80GB PCIe (UUID: GPU-41255406-c9af-f94b-4ebf-9d57ad1853da)
  MIG 2g.20gb     Device  0: (UUID: MIG-a65afc88-50b5-5ccf-b0a8-f93b3247ae9e)
$
```

**Comment by nikkon-dev** [comment]
@starry91,

Unfortunately, when the UUID format for the MIG instances changed, the DCGM was not updated to reflect that. Currently, there is no way to get the proper MIG UUID via DCGM API. 

This is in our backlog.
