### ISSUE TITLE
default makefile build failure

### ISSUE THREAD

**Issue by emeraldbay** [NVIDIA/go-dcgm#36]
ubuntu@ip-172-31-7-67:~/go-dcgm$ make
go build ./pkg/dcgm
go: downloading github.com/bits-and-blooms/bitset v1.2.1
go: downloading github.com/Masterminds/semver v1.5.0
cd samples/deviceInfo; go build
cd samples/dmon; go build
cd samples/health; go build
cd samples/hostengineStatus; go build
cd samples/policy; go build
cd samples/processInfo; go build
cd samples/restApi; go build
go: downloading github.com/gorilla/mux v1.8.0
cd samples/topology; go build
go test ./tests
/tmp/go-build4207065393/b001/tests.test: symbol lookup error: /tmp/go-build4207065393/b001/tests.test: undefined symbol: dcgmGetAllDevices
FAIL	github.com/NVIDIA/go-dcgm/tests	0.003s
FAIL
make: *** [Makefile:32: test-main] Error 1

**Comment by emeraldbay** [comment]
How we are suppose to run the test? Thanks

**Comment by glowkey** [comment]
This error indicates 'libdcgm.so' was not found. That library is included with DCGM and is required for the Go bindings. You can use $LD_LIBRARY_PATH if the library is not picked up by ldconfig.
