### ISSUE TITLE
dyld[33398]: symbol not found in flat namespace '_DcgmFieldGetById'

### ISSUE THREAD

**Issue by vickyvikas7988** [NVIDIA/go-dcgm#39]
I am facing below error while executing the code.

This is specific for M1 Mac user.

How do we resolve it?

> dyld[33398]: symbol not found in flat namespace '_DcgmFieldGetById'

**Comment by glowkey** [comment]
go-dcgm requires libdcgm.so to execute but M1 MacOS is not a supported platform for DCGM.

**Comment by nikkon-dev** [comment]
@vickyvikas7988, 
Unfortunately, Nvidia GPUs are not supported on MacOS, and there are no plans to add DCGM support for that platform.
