### ISSUE TITLE
Where can I get the sample output of various policy failures?

### ISSUE THREAD

**Issue by vinayburugu** [NVIDIA/go-dcgm#43]
I registered the policies and want to handle the policy failures using below example code. Where can I get the sample output of each of the policy failures?
https://github.com/NVIDIA/go-dcgm/blob/main/samples/policy/main.go

**Comment by glowkey** [comment]
There are no specific examples but the existing policy tests and DCGM error injection should help with your development: 

https://github.com/NVIDIA/DCGM/blob/master/testing/python3/tests/test_policy.py https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/dcgm-error-injection.html
