### ISSUE TITLE
Compile error, cannot use _Ctype_long(ts) (value of type _Ctype_long) as _Ctype_longlong

### ISSUE THREAD

**Issue by prtsh** [NVIDIA/go-dcgm#63]
Env - 
1/ go version go1.17.3 darwin/amd64
2/ macos Sonoma 14.3, kern.version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
3/ package - datacenter-gpu-manager-3.3.3-1-x86_64.rpm (link - https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/)

this DCGM package is added as a dependency to another package being build.

Compile failure message - 
```

# github.com/NVIDIA/go-dcgm/pkg/dcgm
../AL2_x86_64/DEV.STD.PTHREAD/build/private/bgospace/Go3p-Github-NVIDIA-Go-dcgm/src/github.com/NVIDIA/go-dcgm/pkg/dcgm/internal.go:80:14: cannot use _Ctype_long(ts) (value of type _Ctype_long) as _Ctype_longlong value in struct literal
make: *** [install] Error 1
```

**Comment by nvvfedorov** [comment]
@prtsh , Please try to use: DCGM v3.3.5 and go 1.21.

**Comment by prtsh** [comment]
updated go to 1.22, didn't work.
I will check with the newer version of DCGM, and post back.

**Comment by prtsh** [comment]
there is a similar issue, which was fixed by changing the golang -> C casting type, is this also needed here?

https://github.com/mraleph/go_dart_ffi_example/pull/2/commits/627479bd3204352364775a6f9b88175bc667dd96

**Comment by prtsh** [comment]
reporting back - Didn't work, still failing with `3.3.5`

**Comment by rohit-arora-dev** [comment]
DCGM and go-dcgm are supported only on Linux, looks like this issue is specific to Darwin OS which is not supported.
DCGM Support page: https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/getting-started.html#supported-platforms

**Comment by prtsh** [comment]
The build used to work before, on `macos Sonoma, 14.3` it started failing after the upgrade to `14.4 (23E214)`

**Comment by prtsh** [comment]
There needs to be change to the go-dcgm package to allow builds across OS types, 

https://stackoverflow.com/questions/70243683/how-to-convert-c-uint64-t-to-cgo-consistently-across-os
