### ISSUE TITLE
cant set -p parameter when using go-dcgm, but cli can

### ISSUE THREAD

**Issue by freelikeff** [NVIDIA/go-dcgm#68]
cli can using like this : dcgmi diag -r 4 --fail-early -p "eud.passthrough_args='run_tests=compute'",          
 but go-dcgm No interface for passing parameters (such as --fail-early or -p paramter )

**Comment by glowkey** [comment]
Correct. The go-dcgm wrapper is much simplified. Please submit a PR if there is functionality you think would benefit the users of go-dcgm.
