### ISSUE TITLE
Darwin ARM64 Compile issue after Upgrading from v0.0.0-20230816170901-d898cc7820fe to v0.0.0-20240118201113-3385e277e49f

### ISSUE THREAD

**Issue by TamerSherif** [NVIDIA/go-dcgm#71]
It appears something broke once we upgraded from version v0.0.0-20230816170901-d898cc7820fe to v0.0.0-20240118201113-3385e277e49f, specifically on _mac arm64_:
```
../../../../go/pkg/mod/github.com/!n!v!i!d!i!a/go-dcgm@v0.0.0-20240118201113-3385e277e49f/pkg/dcgm/internal.go:80:14: cannot use _Ctype_long(ts) (value of type _Ctype_long) as _Ctype_longlong value in struct literal
```
Things still work on ubuntu amd64.

Please advise.

**Comment by nvvfedorov** [comment]
The go-dcgm is not supposed to be build and run on the Mac OS or Windows. The package can be build and tested on the Linux only.
